from __future__ import annotations

APP_NAME = "SteamyLAN"
APP_TAGLINE = "Play together through Steam. No router setup needed."
APP_VERSION = "1.3.0"
APP_DEVELOPER = "noitavoo"
DEFAULT_APP_ID = 480
APP_ID = DEFAULT_APP_ID
GITHUB_REPOSITORY = "noitavoo/SteamyLAN"
PROTOCOL_VERSION = 4


LOBBY_PRIVATE = 0
LOBBY_FRIENDS_ONLY = 1
LOBBY_PUBLIC = 2
LOBBY_INVISIBLE = 3
ERESULT_OK = 1
CHAT_ROOM_ENTER_SUCCESS = 1
FRIEND_IMMEDIATE = 0x04

CALLBACK_PERSONA_STATE_CHANGE = 304
CALLBACK_GAME_LOBBY_JOIN_REQUESTED = 333
CALLBACK_LOBBY_INVITE = 503
CALLBACK_LOBBY_ENTER = 504
CALLBACK_LOBBY_MATCH_LIST = 510
CALLBACK_LOBBY_CREATED = 513
CALLBACK_STEAM_API_CALL_COMPLETED = 703
CALLBACK_NETWORKING_MESSAGES_SESSION_REQUEST = 1251
CALLBACK_NETWORKING_MESSAGES_SESSION_FAILED = 1252

LOBBY_DATA_MARKER_KEY = "SteamyLan"
LOBBY_DATA_MARKER_VALUE = "1"
LOBBY_DATA_CONFIG_KEY = "SteamyLan_config"
LOBBY_DATA_VERSION_KEY = "SteamyLan_version"
LOBBY_DATA_NAME_KEY = "SteamyLan_name"
LOBBY_DATA_VISIBILITY_KEY = "SteamyLan_visibility"
LOBBY_DATA_MAX_KEY = "SteamyLan_max"
LOBBY_DATA_MEMBER_COUNT_KEY = "SteamyLan_members"
LOBBY_DATA_INVITE_HASH_KEY = "SteamyLan_invite_hash"
LOBBY_DATA_STATIC_HASH_KEY = "SteamyLan_static_hash"

VISIBILITY_PUBLIC = "public"
VISIBILITY_FRIENDS = "friends"
VISIBILITY_INVITE = "invite"
VISIBILITY_VALUES = {VISIBILITY_PUBLIC, VISIBILITY_FRIENDS, VISIBILITY_INVITE}



STEAM_SEND_UNRELIABLE_NO_NAGLE = 1
STEAM_SEND_RELIABLE_NO_NAGLE = 9
STEAM_SEND_AUTO_RESTART_BROKEN_SESSION = 32

MAGIC = b"STLN"
MAX_STEAM_PACKET = 128 * 1024
TCP_CHUNK = 48 * 1024

PT_HELLO = 1
PT_AUTH_REQUEST = 2
PT_AUTH_GRANTED = 3
PT_AUTH_DENIED = 4
PT_ACCESS_REVOKED = 5
PT_DISCONNECTED = 6
PT_DISCONNECT_ACK = 7
PT_CONFIG_UPDATE = 8
PT_HEARTBEAT = 9
PT_OPEN_TCP = 10
PT_DATA = 11
PT_CLOSE = 12
PT_UDP = 13
PT_HEARTBEAT_ACK = 14
PT_CHAT_HELLO = 20
PT_CHAT_HELLO_ACK = 21
PT_CHAT_MESSAGE = 22
PT_INVITE_REQUEST = 30
PT_INVITE_GRANTED = 31
PT_INVITE_DENIED = 32

PROTO_NONE = 0
PROTO_TCP = 1
PROTO_UDP = 2
PROTO_CHAT = 3
PROTO_INVITE = 4

CHANNEL_MIN = 10_000
CHANNEL_MAX = 30_000
CONTROL_CHANNEL_MIN = 30_001
CONTROL_CHANNEL_MAX = 39_000
CHAT_CHANNEL_MIN = 39_001
CHAT_CHANNEL_MAX = 47_000
INVITE_CHANNEL = 47_001

AUTO_DISCOVERY_INTERVAL_MS = 8_000
SERVICE_SCAN_INTERVAL_MS = 5_000
MEMBER_SCAN_INTERVAL_MS = 1_000
AUTH_RETRY_SECONDS = 1.5
PUBLIC_LOBBY_RESULT_LIMIT = 50
CHAT_TEXT_MAX = 1800


LOBBY_CONFIG_MAX_BYTES = 7600
